require 'spec_helper'

describe ValidateZipcode do
  it "all countries" do
    expect(ValidateZipcode::Validator.new("1234", "AF").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "AL").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "AD").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "AU").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "AT").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "BD").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "BE").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "BO").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "BG").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "CV").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "CY").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "DK").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "ET").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "GE").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "GW").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "HM").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "HU").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "MK").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "LR").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "LI").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "VE").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "TN").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "CH").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "SJ").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "PH").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "PY").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "NO").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "MZ").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "NZ").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "NE").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "SI").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234", "ZA").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("123456", "BY").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345678", "BR").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("H3Z2Y7", "CA").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234567", "CL").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("123456", "CN").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("123456", "CO").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "CR").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "HR").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "CU").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "DE").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "EE").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "FI").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "FR").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "GR").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("123456", "IN").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "ID").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "IQ").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "IL").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "IT").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234567", "JP").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("123456", "KZ").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("123456", "KG").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "MH").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "MX").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "MC").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "MN").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "NA").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "NP").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "PE").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("1234567", "PT").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("123456", "RO").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("123456", "RU").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "SA").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "SN").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("123456", "SG").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "ES").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "LK").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "SD").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("123456", "TJ").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "TH").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("123456", "TT").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "TR").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("123456", "TM").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "UA").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("123456789", "US").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("123456", "UZ").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("123456", "VN").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "VI").valid?).to be_truthy
    expect(ValidateZipcode::Validator.new("12345", "ZM").valid?).to be_truthy
  end
end
